[product-9] Replace converter classes of Product package with Mapstruct
Sunagatov/Online-Store pull request #82
Opened 2023-08-16 15:51 UTC by vitaliibredun

![Screenshot 2023-08-18 at 23 21 39](https://github.com/Sunagatov/Online-Store/assets/101927617/909a3cd7-89bb-411d-b917-279580405c59)
1. Task's name: 
[cart-12] Replace converter classes of Product package with Mapstruct

 2. Developer's full name: 
Vitalii Bredun

 3. Link to the PR: 
https://github.com/Sunagatov/Online-Store/pull/82

 4. Link to Documentation: 
https://github.com/Sunagatov/Online-Store/wiki/API-Specification-for-Product

 5. Changes: 
- Added the Mapstruct interfaces to the converter package.
- Deleted the custom mapper classes.
- Added tests for the Mapstruct.
                                                                                                                                                                                          
 6. Tests: 
ProductInfoDtoConverterTest is checking the mapping.

 7. Test data: 
In the product package of the test package.

 8. Conclusion: 
Project was built with Apache Maven successfully.

2023-08-16 16:12 UTC, Sanya124 approved these changes

2023-08-17 03:14 UTC, UladzislauM approved these changes

2023-08-22 16:41 UTC, vpshvd requested changes

2023-08-22 16:42 UTC, vpshvd requested changes

2023-08-22 16:42 UTC, vpshvd commented on src/main/java/com/zufar/onlinestore/product/converter/ProductInfoDtoConverter.java
>  }
Add empty line at the end of this file

2023-08-23 20:13 UTC, vitaliibredun commented on src/test/java/com/zufar/onlinestore/ProductInfoDtoConverterTest.java
> +package com.zufar.onlinestore;
done

2023-08-23 20:13 UTC, vitaliibredun commented on src/main/java/com/zufar/onlinestore/product/converter/ProductInfoDtoConverter.java
>  }
done

2023-08-23 20:38 UTC, vpshvd approved these changes

2023-08-23 20:41 UTC, AiratGimaev approved these changes
Approved

2023-08-23 20:42 UTC, AiratGimaev approved these changes
Approved

2023-08-23 22:25 UTC, Sunagatov approved these changes

2023-08-23 22:25 UTC, merged